version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlFlowCraft
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./backups:/var/opt/mssql/backup
  app:
    image: front
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  sqlserver-data:
    driver: local

# creo la conexion con dbeaber o lo que sea 
# host: localhost
# port: 1433
# user: sa
# password : YourStrong!Passw0rd



